### ISSUE TITLE
 environment.__STATIC_CONTENT.put(key, rendered.body) doesn't seem to be working?

### ISSUE THREAD

**Issue by kmcaloon** [reegodev/sveltekit-isr#1]
Thanks for the awesome blog post and info. I'm using a modified version of your worker in a standard CF Worker, but it is giving me the following error without anything else that is all that helpful.

```
Error rendering route: Cannot read properties of undefined (reading 'put')
```
I'm assuming this is related to your method ` environment.__STATIC_CONTENT.put(key, rendered.body)`

Kind of stuck here. This should be available by default to all Workers correct? I'm just using a standard worker (nothing related to Cloudflare Pages). Should we be setting anything up in our Workers KV dashboard?

**Comment by reegodev** [comment]
Hi @kmcaloon , yes it seems the KV binding has not been created for your worker, are you using `wrangler publish` to deploy your website? As far as i am aware, that indeed is the default KV binding created for static assets.
You can also check the KV settings for your worker on the Cloudflare dashboard by going on Workers (right sidebar) -> [name of your worker] -> Settings tab -> Variables on the left sidebar -> scroll down to KV Namespace Bindings section

**Comment by kmcaloon** [comment]
Thanks @reegodev, I actually wasn't deploying via wrangler. I've noticed some differences between your blog post and repo code. I'll use both to help me through it thanks.
